HouseMe/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.http import JsonResponse
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from typing import List

from account import views as account_view
from account.models import User


class UsersListView(LoginRequiredMixin, ListView):
    http_method_names = [
        "get",
    ]

    def get_queryset(self):
        return User.objects.all().exclude(id=self.request.user.id)

    def render_to_response(self, context, **response_kwargs):
        users: List[AbstractBaseUser] = context["object_list"]

        data = [{"username": user.get_username(), "pk": str(user.pk)} for user in users]
        return JsonResponse(data, safe=False, **response_kwargs)


urlpatterns = [
    path("property/", include("Property.urls")),
    path("admin/", admin.site.urls),
    path("register/", account_view.register, name="register"),
    path("profile/", account_view.profile, name="profile"),
    path("", include("Property.urls")),
    path("account/", include("account.urls", namespace="account")),
    path("users/", UsersListView.as_view(), name="users_list"),
    re_path(
        r"", include("django_private_chat2.urls", namespace="django_private_chat2")
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "HouseMe.views.page_not_found_view"

Property/urls.py
from django.urls import path
from . import views


app_name = "property"
urlpatterns = [
    path("", views.index, name="index"),
    path("browselistings", views.browselistings, name="browselistings"),
    path("newlisting", views.newlisting, name="newlisting"),
    path("mylistings", views.mylistings, name="mylistings"),
    path("editlisting/<int:listing_id>", views.editlisting, name="editlisting"),
    path("<int:listing_id>", views.propertypage, name="propertypage"),
    path("filter/borough/<borough>", views.filterborough, name="filterborough"),
    path("filter", views.filter, name="filter"),
    path("comment/<int:property_id>", views.comment, name="comment"),
    path("newcomment/<int:property_id>", views.newcomment, name="newcomment"),
    path("newrating/<int:property_id>", views.newrating, name="newrating"),
    path("delete/<int:listing_id>", views.delete_post, name="delete"),
    path("charts/<borough>", views.charts, name="charts"),
    path("sortby/<attribute>", views.sortby, name="sortby"),
]

account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("loginform", views.loginform, name="loginform"),
    # path("loginsubmit", views.loginsubmit, name="loginsubmit"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="account/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="account/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("sign-out", views.sign_out, name="sign-out"),
]

django_private_chat2/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.urls import path, re_path
from . import consumers
from . import views

app_name = "django_private_chat2"
websocket_urlpatterns = [
    re_path(r"^chat_ws$", consumers.ChatConsumer.as_asgi()),
]

urlpatterns = [
    path("messages/", views.MessagesModelList.as_view(), name="all_messages_list"),
    path(
        "messages/<dialog_with>/",
        views.MessagesModelList.as_view(),
        name="messages_list",
    ),
    path("dialogs/", views.DialogsModelList.as_view(), name="dialogs_list"),
    path("self/", views.SelfInfoView.as_view(), name="self_info"),
    path("upload/", views.UploadView.as_view(), name="fileupload"),
    path(
        "chat/",
        login_required(TemplateView.as_view(template_name="chat/chat.html")),
        name="chat",
    ),
]

templates/partials/footer.html
  <!-- Footer -->
  <footer class="text-center text-white" style="background-color: black; padding: 1rem;
  position: relative;" id="footer">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="{% url 'property:index' %}">HouseMe</a>

    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

templates/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'property:index' %}">HouseMe</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav me-auto">
                <a class="nav-link" href="{% url 'property:browselistings' %}">Browse Listings</a>
            </div>
            <div class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% load thumbnail %}
                            <img class="rounded-circle" src="{{ user.profile.image.nav.url}}">
                            {{ user.username }} 
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink" onclick="event.stopPropagation()">
                            <li><a class="dropdown-item disabled">{{ user.first_name }} {{user.last_name}}</a></li>
                            <li><a class="dropdown-item " href="{% url 'profile'%}">Profile</a></li>
                            <li><a class="dropdown-item " href="{% url 'django_private_chat2:chat'%}">Chat</a></li>
                            <div class="dropdown-divider"></div>

                            <li><a class="dropdown-item" href="{% url 'property:mylistings' %}">My listings</a></li>
                            <li><a class="dropdown-item" href="{% url 'property:newlisting' %}">New listing</a></li>

                            <div class="dropdown-divider"></div>
                            
                            <li><a class="dropdown-item" href="{% url 'account:sign-out' %}">Sign out</a></li>
                        </ul>
                    </li>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'account:loginform' %}" role="button">Log In</a>
                    <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                {% endif%}
            </div>
        </div>
    </div>
</nav>