HouseMe/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.http import JsonResponse
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from typing import List

from account import views as account_view
from account.models import User


class UsersListView(LoginRequiredMixin, ListView):
    http_method_names = [
        "get",
    ]

    def get_queryset(self):
        return User.objects.all().exclude(id=self.request.user.id)

    def render_to_response(self, context, **response_kwargs):
        users: List[AbstractBaseUser] = context["object_list"]

        data = [{"username": user.get_username(), "pk": str(user.pk)} for user in users]
        return JsonResponse(data, safe=False, **response_kwargs)


urlpatterns = [
    path("property/", include("Property.urls")),
    path("admin/", admin.site.urls),
    path("register/", account_view.register, name="register"),
    path("profile/", account_view.profile, name="profile"),
    path("", include("Property.urls")),
    path("account/", include("account.urls", namespace="account")),
    path("users/", UsersListView.as_view(), name="users_list"),
    re_path(
        r"", include("django_private_chat2.urls", namespace="django_private_chat2")
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "HouseMe.views.page_not_found_view"

Property/urls.py
from django.urls import path
from . import views


app_name = "property"
urlpatterns = [
    path("", views.index, name="index"),
    path("browselistings", views.browselistings, name="browselistings"),
    path("newlisting", views.newlisting, name="newlisting"),
    path("mylistings", views.mylistings, name="mylistings"),
    path("editlisting/<int:listing_id>", views.editlisting, name="editlisting"),
    path("<int:listing_id>", views.propertypage, name="propertypage"),
    path("filter/borough/<borough>", views.filterborough, name="filterborough"),
    path("filter", views.filter, name="filter"),
    path("comment/<int:property_id>", views.comment, name="comment"),
    path("newcomment/<int:property_id>", views.newcomment, name="newcomment"),
    path("newrating/<int:property_id>", views.newrating, name="newrating"),
    path("delete/<int:listing_id>", views.delete_post, name="delete"),
    path("charts/<borough>", views.charts, name="charts"),
    path("sortby/<attribute>", views.sortby, name="sortby"),
]

Property/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


# Create your models here.


class Listing(models.Model):
    listing_id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    address1 = models.CharField(
        # verbose_name="Address_1", max_length=100, null=True, blank=True
        verbose_name="Address_1",
        max_length=100,
    )
    address2 = models.CharField(
        verbose_name="Address_2", max_length=120, null=True, blank=True
    )
    borough = models.CharField(
        verbose_name="Borough", max_length=120, null=True, blank=True
    )
    zipcode = models.CharField(
        verbose_name="Zip Code", max_length=8, null=True, blank=True
    )
    longitude = models.CharField(
        verbose_name="Longitude", max_length=50, null=True, blank=True
    )
    latitude = models.CharField(
        verbose_name="Latitude", max_length=50, null=True, blank=True
    )
    rent = models.IntegerField(verbose_name="Rent", default=1)
    area = models.FloatField(verbose_name="Area", default=0)
    bedrooms = models.IntegerField(verbose_name="Bedrooms", default=1)
    bathrooms = models.IntegerField(verbose_name="Bathrooms", default=1)
    furnished = models.BooleanField(verbose_name="Furnished", default=False)
    elevator = models.BooleanField(verbose_name="Elevator", default=False)
    heating = models.BooleanField(verbose_name="Heating", default=False)
    parking = models.BooleanField(verbose_name="Parking", default=False)
    laundry = models.BooleanField(verbose_name="Laundry", default=False)
    matterport_link = models.URLField(
        verbose_name="Matterport_Link", max_length=300, null=True, blank=True
    )
    photo_url = models.ImageField(
        upload_to="media/", verbose_name="Upload Primary Image", null=True, blank=True
    )
    photo_url2 = models.ImageField(
        upload_to="media/", null=True, verbose_name="Upload Second Image", blank=True
    )
    photo_url3 = models.ImageField(
        upload_to="media/", null=True, verbose_name="Upload Third Image", blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name", max_length=100, null=True, blank=False)
    description = models.TextField(verbose_name="Description", null=True, blank=True)
    active = models.BooleanField(default=False)
    ratings = models.FloatField(default=1, null=True, blank=True)
    # slug = models.SlugField(slugify(address1))

    def __str__(self) -> str:
        return f"owner: {self.owner} \n address:{self.address1} {self.address2}"


def get_image_filename(instance, filename):
    title = instance.listing.name
    slug = slugify(title)
    return "post_images/%s-%s" % (slug, filename)


class Rating(models.Model):
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    value = models.FloatField(max_length=100)


class Comment(models.Model):
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    text = models.CharField(max_length=100)


# class Images(models.Model):

#   listing = models.ForeignKey(Listing, on_delete=models.CASCADE, null=True, blank=True)
#  image = models.FileField(upload_to="media/", verbose_name='Image')


class RequestTour(models.Model):
    requester = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, null=True, blank=True, default=-1
    )

    firstName = models.CharField(
        verbose_name="First Name", max_length=32, null=False, blank=False, default="N/A"
    )
    lastName = models.CharField(
        verbose_name="Last Name", max_length=32, null=False, blank=False, default="N/A"
    )
    email = models.EmailField(
        verbose_name="Email", null=False, blank=False, default="N/A"
    )
    phone = models.CharField(verbose_name="Phone", max_length=12, null=True, blank=True)
    message = models.CharField(
        verbose_name="Message", max_length=500, null=True, blank=True
    )
    tourDate = models.DateField(
        verbose_name="Tour Date", null=False, blank=False, default=datetime.now
    )

Property/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Listing, Comment, Rating
from django.contrib.auth.models import User
from .forms import ListingForm, RequestTourForm, CommentForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.core.mail import send_mail  # , BadHeaderError
from django.conf import settings
import plotly.express as px
import pandas as pd


from django.db.models import Avg

# TODO validate email
# from django.core.validators import validate_email
# from django.core.exceptions import ValidationError


def index(request):
    return render(request, "property/index.html")


def browselistings(request):
    listings = Listing.objects.all().order_by("rent")
    return render(request, "property/browselistings.html", {"listings": listings})


@login_required(login_url="/account/loginform")
def newlisting(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = ListingForm(request.POST, request.FILES or None)
        # check whether it's valid:
        if form.is_valid():
            obj = form.save()
            if request.user is not None:
                user = request.user
                obj.owner = user
                obj.save()
                print("new listing post successful")
            else:
                print("unknown user listing")

        else:
            print(form.errors)
            result = "Failed"
            message = "Failed to save listings form"
            data = {"result": result, "message": message}
            print(data)
            messages.error(request, form.errors)
            return redirect(reverse("property:newlisting"))
        return redirect(reverse("property:mylistings"))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ListingForm()
        context = {"form": form}
        context["google_api_key"] = settings.GOOGLE_API_KEY
        context["base_country"] = settings.BASE_COUNTRY
    return render(request, "property/newlisting.html", context)


@login_required(login_url="/account/loginform")
def editlisting(request, listing_id):
    listing = get_object_or_404(Listing, listing_id=listing_id)
    if request.user != listing.owner:
        return HttpResponseRedirect("../browselistings")
    if request.method == "POST":
        form = ListingForm(request.POST, request.FILES, instance=listing)
        if form.is_valid():
            form.save()
            print("edit listing successful")
        else:
            print(form.errors)
            result = "Failed"
            message = "Failed to save listings form"
            data = {"result": result, "message": message}
            print(data)
            messages.error(request, form.errors)
            return redirect(reverse("property:editlisting"))
        return redirect(reverse("property:mylistings"))
    else:
        form = ListingForm(instance=listing)
        context = {"form": form}
        context["google_api_key"] = settings.GOOGLE_API_KEY
        context["base_country"] = settings.BASE_COUNTRY
        context["listing_id"] = listing_id
        return render(request, "property/editlisting.html", context)


@login_required(login_url="/account/loginform")
def mylistings(request):
    user_listings = Listing.objects.filter(owner=request.user)
    return render(request, "property/mylistings.html", {"listings": user_listings})


def propertypage(request, listing_id):
    if request.method == "POST":
        listing = Listing.objects.get(listing_id=listing_id)
        form = RequestTourForm(
            request.POST, request.FILES or None, user=request.user, listing=listing
        )
        if form.is_valid():
            obj = form.save(commit=False)
            if request.user.is_authenticated:
                obj.requester = User.objects.get(username=request.user.username)
            obj.listing = listing
            obj.firstName = (
                request.POST.get("firstName")
                if request.POST.get("firstName")
                else form["firstName"].value()
            )
            obj.lastName = (
                request.POST.get("lastName")
                if request.POST.get("lastName")
                else form["lastName"].value()
            )
            obj.email = (
                request.POST.get("email")
                if request.POST.get("email")
                else form["email"].value()
            )
            obj.phone = (
                request.POST.get("phone")
                if request.POST.get("phone")
                else form["phone"].value()
            )
            obj.message = request.POST.get("message")
            obj.tourDate = request.POST.get("tourDate")

            obj.save()
            sub = (
                "A User has requested to view your property at :"
                + " "
                + obj.listing.address1
            )
            ph = obj.phone
            message = (
                obj.message
                + "\n\n"
                + "Contact details of the user:"
                + "\n"
                + obj.firstName
                + " "
                + obj.lastName
                + "\n"
                + obj.email
                + "\n"
                + str(ph)
                + "\n"
                + "Tour date requested:"
                + " "
                + obj.tourDate
                + "\n\n"
                + "Thanks and Have a Great Day!"
            )
        send_mail(
            subject=sub,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[listing.owner.email],
            fail_silently=False,
        )

        successMessage = "You have successfully requested a tour!"
        messages.info(request, successMessage)
        property_id = listing.listing_id
        comments = Comment.objects.filter(listing=property_id)
        print("Comments", comments)
        comment_form = CommentForm()
        listing_rating = Listing.objects.filter(listing_id=property_id)[0].ratings
        context = context = {
            "listing": listing,
            "successMessage": successMessage,
            "form": form,
            "comments": comments,
            "property_id": property_id,
            "listing_rating": listing_rating,
            "comment_form": comment_form,
        }
        return render(request, "property/property_page.html", context)
    else:
        listing = Listing.objects.get(listing_id=listing_id)
        form = RequestTourForm(user=request.user, listing=listing)
        property_id = listing.listing_id
        comments = Comment.objects.filter(listing=property_id)
        print("Comments", comments)
        comment_form = CommentForm()
        listing_rating = Listing.objects.filter(listing_id=property_id)[0].ratings
        context = {
            "listing": listing,
            "form": form,
            "comments": comments,
            "property_id": property_id,
            "listing_rating": listing_rating,
            "comment_form": comment_form,
            "google_api_key": settings.GOOGLE_API_KEY,
        }
        return render(request, "property/property_page.html", context)


def filterborough(request, borough):
    listings = Listing.objects.filter(borough=borough)
    return render(request, "property/browselistings.html", {"listings": listings})


def sortby(request, attribute):
    listings = Listing.objects.order_by("-" + attribute)
    return render(request, "property/browselistings.html", {"listings": listings})


def filter(request):
    filters = request.POST.getlist("filters")
    if "furnished" in filters:
        furnished = True
    else:
        furnished = False
    if "elevator" in filters:
        elevator = True
    else:
        elevator = False
    if "heating" in filters:
        heating = True
    else:
        heating = False
    if "parking" in filters:
        parking = True
    else:
        parking = False
    if "laundry" in filters:
        laundry = True
    else:
        laundry = False
    if "verified" in filters:
        active = True
    else:
        active = False
    print(filters)
    listings = Listing.objects.filter(
        furnished=furnished,
        elevator=elevator,
        heating=heating,
        parking=parking,
        laundry=laundry,
        active=active,
    )
    return render(request, "property/browselistings.html", {"listings": listings})


@login_required(login_url="/account/loginform")
def comment(request, property_id):
    # property_id = 1
    comments = Comment.objects.filter(listing=property_id)
    comment_form = CommentForm()
    listing_rating = Listing.objects.filter(listing_id=property_id)[0].ratings
    print("listing_rating", listing_rating)
    return render(
        request,
        "property/comments.html",
        {
            "comments": comments,
            "property_id": property_id,
            "comment_form": comment_form,
            "listing_rating": listing_rating,
        },
    )


@login_required(login_url="/account/loginform")
def newcomment(request, property_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            obj = form.save()
            if request.user is not None:
                user = request.user
                obj.user = user
                listing = Listing.objects.filter(listing_id=property_id)[0]
                obj.listing = listing
                obj.save()
                listing_id = listing.listing_id
                address1 = listing.address1
                print(address1)
    return redirect(reverse("property:propertypage", kwargs={"listing_id": listing_id}))

templates/property/browselistings.html
{% extends 'base.html'%}
{% load static %}

{% block extend_head %}
<link rel="stylesheet" href="{% static 'css/style.css' %}"> 
<link rel="stylesheet" href="{% static 'css/browselistings.css' %}">
{% endblock %}

{% block content %}
<br>
<div class="container-lg">
  <div class="row">
    <div class="col-lg-4">
      <div class="card" style="padding: 10%; text-align: center; color: black;">
        Sort by
        <hr>
        <div class="container-fluid" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100" href="{% url 'property:sortby' 'rent' %}">Rent</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:sortby' 'area' %}">Area</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:sortby' 'ratings' %}">Ratings</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:sortby' 'bedrooms' %}">Bedrooms</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:sortby' 'bathrooms' %}">Bathrooms</a>
        </div>
        <br>

        Filter by Borough
        <hr>
        <div class="container-fluid" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100" href="{% url 'property:filterborough' 'Manhattan' %}">Manhattan</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:filterborough' 'Brooklyn' %}">Brooklyn</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:filterborough' 'Queens' %}">Queens</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:filterborough' 'Bronx' %}">Bronx</a>
        </div>
        <div class="" style="padding: 1%;">
          <a class="btn btn-primary btn-sm w-100"  href="{% url 'property:filterborough' 'Staten Island' %}">Staten Island</a>
        </div>
        <br>
        <div class="">
          Other Filters
          <hr>
          <form method="POST" action = "{% url 'property:filter' %}">
              {% csrf_token %}

          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="furnished" name="filters">
            <label class="form-check-label" for="furnished">
              Furnished
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="elevator" name="filters">
            <label class="form-check-label" for="elevator">
              Elevator
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="heating" name="filters">
            <label class="form-check-label" for="heating">
              Heating
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="parking" name="filters">
            <label class="form-check-label" for="parking">
              Parking
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="laundry" name="filters">
            <label class="form-check-label" for="laundry">
              Laundry
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="verified" name="filters">
            <label class="form-check-label" for="verified">
              Verified
            </label>
          </div>
          <br>
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
        </div>
      </div>
    </div>

    <div class="col-lg-8">
      {% for listing in listings%}
      <div class="card mb-3" style="max-width: 720px; max-height: 200px; margin: 25px 25px 25px 25px ">
        <div class="row g-0">
          <div class="col-md-4">
            {% if listing.photo_url %}
            <img class="rounded-start cropped" src="{{listing.photo_url.url}}" alt="...">
            {% else %}
            <img src="https://via.placeholder.com/300" class="img-fluid rounded-start" alt="...">
            {% endif %}
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{listing.address1}} {% if listing.address2 %} {{listing.address2}} {% endif %}
                {% if listing.active %}
                <i class="fa fa-check fa-sm" style="color:green;object-fit:contain;"></i>
                {% endif %}
              </h5>
              <div class="row">
                <div class="col-md-4"> Zip Code: {{listing.zipcode}} </div>
                <div class="col-md-4"> Borough: {{listing.borough}} </div>
                <div class="col-md-4"> Rent: $ {{listing.rent}} </div>
              </div>
              <div class="row">
                <div class="col-md-4"> Bedroom: {{listing.bedrooms}} </div>
                <div class="col-md-4"> Bathroom: {{listing.bathrooms| stringformat:".2f" }}</div>
                <div class="col-md-4"> Area : {{listing.area}} Sq</div>
              </div>

              <br>
              <div class="d-flex align-items-end">
                <a class="btn btn-primary" href="/property/{{listing.listing_id}}" role="button">View</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<br>


{% endblock %}

{% block extend_footer %}

{% endblock %}

templates/property/chart.html
{% extends 'base.html' %}

{% block content %}
    {{ disp|safe }}
{% endblock content %}

templates/property/comments.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<body>
    <div class="container" style="padding: 2%;">
      <div class="">
        <form id = 'ratingsform' method="POST" action = "{% url 'property:newrating' property_id %}">
            {% csrf_token %}
            <label for="rating_value" class="form-label">Rating</label>
            <input name="rating_value" type="range" class="form-range" min="0" max="5" step="0.5" id="rating_value">
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
      </div>
      <div class="list-group">
        {% for comment in comments %}
        <a href="#" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{comment.text}}</h5>
            <small>{{comment.created_at}}</small>
          </div>
          <p class="mb-1">Some placeholder content in a paragraph.</p>
          <small>- {{comment.user.first_name}} {{comment.user.last_name}}</small>
        </a>
        {% endfor %}
      </div>
    </div>
    <div class="" style="padding: 5%;">
      <div class="container"  style="padding: 2%;">
        <form id = 'listingform' method="POST" enctype="multipart/form-data" action = "{% url 'property:newcomment' property_id %}">
          {% load crispy_forms_tags %}
            {% csrf_token %}
            {{ comment_form|crispy}}
            <button type="submit" class="btn btn-success">Submit</button>
        </form>

      </div>

  </div>


</body>

</html>

templates/property/mylistings.html
{% extends 'base.html'%}
{% load static %}
{% block extend_head %}
<link rel="stylesheet" href="{% static 'css/browselistings.css' %}">
{% endblock %}
{% block content %}
<div class="container-lg">

    <h2 class="mt-3 mb-3"> My listings</h2>
    <div class="row">
        <div class="col-lg-8">
            {% for listing in listings%}
            <div class="card mb-3 ps-3" style="max-width: 720px; max-height: 250px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        {% if listing.photo_url %}
                        <img class="rounded-start cropped" src="{{listing.photo_url.url}}" alt="...">
                        {% else %}
                        <img src="https://via.placeholder.com/300" class="img-fluid rounded-start" alt="...">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <div class="row pb-3">
                                <div class="col-md-6">
                                    <h5 class="card-title text-break"> {{listing.address1}} {% if listing.address2 %} {{listing.address2}} {% endif %}
                                        {% if listing.active %}
                                        <i class="fa fa-check fa-sm" style="color:green;object-fit:contain;"></i>
                                        {% endif %}
                                    </h5>
                                </div>
                                <div class="col-md-6">
                                    <div class="float-end text-break">
                                        <span>{{listing.address1}} {% if listing.address2 %} {{listing.address2}} {% endif %}</span>
                                        <div>
                                            <span>
                                                {{listing.zipcode}}
                                                {{listing.borough}}
                                                <span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4"> Bedroom: {{listing.bedrooms}} </div>
                                <div class="col-md-4"> Bathroom: {{listing.bathrooms}}</div>
                                <div class="col-md-4"> Area : {{listing.area}} Sq</div>
                            </div>
                            <div class="row">
                                <div class="col-md-4"> Furnished: {{listing.furnished}} </div>
                                <div class="col-md-4"> Laundry: {{listing.laundry}}</div>
                                <div class="col-md-4"> Heating: {{listing.heating}} </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4"> Parking: {{listing.parking}} </div>
                                <div class="col-md-4"> Elevator: {{listing.elevator}}</div>
                            </div>
                            <div class="d-flex align-items-end">
                                <a class="btn btn-primary" href="{{listing.listing_id}}" role="button"
                                    style="margin: 2px 2px 2px 2px">View</a>
                                <a class="btn btn-secondary " style="margin: 2px 2px 2px 2px"
                                    href="{% url 'property:editlisting' listing.listing_id %}" role="button"
                                    style="margin: 2px 2px 2px 2px">Edit</a>
                                <form method="POST" action="{% url 'property:delete' listing.listing_id %}"
                                    onsubmit="return confirm('Are you sure you want to delete your listing?')">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-secondary" target="_blank"
                                        style="margin: 2px 2px 2px 2px" value="Delete Listing"></a>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block extend_footer %}

{% endblock %}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script>
    function confirm() {

        swal({

                title: 'Warning!',

                text: 'do you want to delete?',

                icon: 'warning',

                showCancelButton: true,

                confirmButtonColor: '#3085d6',

                cancelButtonColor: '#d33',

                cancelButtonText: 'No',

                confirmButtonText: 'Yes'

            },

            function (isConfirm) {

                if (isConfirm) {

                    document.querySelector(del).submit();

                }

            })

    }
</script>